<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-23T15:04:27 IST" name="Default suite" finished-at="2024-11-23T15:04:40 IST" duration-ms="12780">
    <groups>
    </groups>
    <test started-at="2024-11-23T15:04:27 IST" name="Default test" finished-at="2024-11-23T15:04:40 IST" duration-ms="12780">
      <class name="FrameworkDesign.Tests.ErrorValidations">
        <test-method is-config="true" signature="launchApp()[pri:0, instance:FrameworkDesign.Tests.ErrorValidations@7f3b84b8]" started-at="2024-11-23T15:04:27 IST" name="launchApp" finished-at="2024-11-23T15:04:33 IST" duration-ms="5272" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="loginErrorValidation()[pri:0, instance:FrameworkDesign.Tests.ErrorValidations@7f3b84b8]" started-at="2024-11-23T15:04:33 IST" name="loginErrorValidation" finished-at="2024-11-23T15:04:33 IST" duration-ms="958" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:FrameworkDesign.Tests.ErrorValidations@7f3b84b8]" started-at="2024-11-23T15:04:33 IST" name="tearDown" finished-at="2024-11-23T15:04:34 IST" duration-ms="200" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:FrameworkDesign.Tests.ErrorValidations@7f3b84b8]" started-at="2024-11-23T15:04:34 IST" name="launchApp" finished-at="2024-11-23T15:04:38 IST" duration-ms="4815" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="productErrorValidation()[pri:0, instance:FrameworkDesign.Tests.ErrorValidations@7f3b84b8]" started-at="2024-11-23T15:04:38 IST" name="productErrorValidation" finished-at="2024-11-23T15:04:40 IST" duration-ms="1270" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at FrameworkDesign.Tests.ErrorValidations.productErrorValidation(ErrorValidations.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:FrameworkDesign.Tests.ErrorValidations@7f3b84b8]" started-at="2024-11-23T15:04:40 IST" name="tearDown" finished-at="2024-11-23T15:04:40 IST" duration-ms="217" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- FrameworkDesign.Tests.ErrorValidations -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
